runtime: python39
entrypoint: gunicorn -b :$PORT -w 4 --timeout 120 app:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  FLASK_ENV: production
  DATABASE_URL: "sqlite:///link_organizer.db"

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /.*
    script: auto
    secure: always 